export interface InspectionRoof {
  // Keys
  Id: number
  PropertyInspectionFormId: number

  // Dates
  CreatedOn: Date
  LastModifiedOn: Date

  // Booleans
  AllPhotosPitch: boolean
  AllPhotosShingle: boolean
  BlisterDamage: boolean
  BrittlenessTestConducted: boolean
  BrittlenessTestEast: boolean
  BrittlenessTestNorth: boolean
  BrittlenessTestRequested: boolean
  BrittlenessTestSouth: boolean
  BrittlenessTestWest: boolean
  CloggedGutterDamage: boolean
  ContractorPresent: boolean
  ContractorPresentOnRoof: boolean
  CuppedDamage: boolean
  DeckingRottedDamage: boolean
  DripEdgeEavePainted: boolean
  DripEdgeEavePresent: boolean
  DripEdgeRakePainted: boolean
  DripEdgeRakePresent: boolean
  EagleViewProvided: boolean
  EaveStarter: boolean
  ExcessiveWeathering: boolean
  ExposedFasteners: boolean
  Felt: boolean
  FlashingNotSealedDamage: boolean
  GranuleLossDamage: boolean
  GutterEastDamaged: boolean
  GutterNorthDamaged: boolean
  GutterPainted: boolean
  GutterPresent: boolean
  GuttersDamagedNoEast: boolean
  GuttersDamagedNoNorth: boolean
  GuttersDamagedNoSouth: boolean
  GuttersDamagedNoWest: boolean
  GuttersDamagedYesEast: boolean
  GuttersDamagedYesNorth: boolean
  GuttersDamagedYesSouth: boolean
  GuttersDamagedYesWest: boolean
  GutterSouthDamaged: boolean
  GutterWestDamaged: boolean
  HancockDisagreesHailDamage: boolean
  IceWaterShield: boolean
  InstallationError: boolean
  InsuredPresent: boolean
  LaAccompanied: boolean
  LaOnTime: boolean
  ManufacturedDamage: boolean
  ManufacturedMarkDamage: boolean
  MechanicalDamage: boolean
  MechanicalMarkDamage: boolean
  NailPopDamaged: boolean
  OaInitialsCaptured: boolean
  OaInitialsRequired: boolean
  OaReview: boolean
  OtherConditions: boolean
  OutBuildingDamage: boolean
  OutsideAdjusterOnEdge: boolean
  OutsideAdjusterOnLadder: boolean
  OutsideAdjusterPresent: boolean
  OutsideAdjusterPresentOnRoof: boolean
  PublicAdjusterPresent: boolean
  PublicAdjusterPresentOnRoof: boolean
  RakeStarter: boolean
  RodentDamage: boolean
  RoleExplained: boolean
  RoofDebrisDamaged: boolean
  RoofDiagramed: boolean
  RoofMeasured: boolean
  RoofRotted: boolean
  RopeHarness: boolean
  ShingleExposureSf: boolean
  SpatterMarks: boolean
  StormDamage: boolean
  TarpInstall: boolean
  TarpReset: boolean
  ThermalCrackingDamage: boolean
  ValleyMetalPainted: boolean
  ValleyMetalPresent: boolean

  // Bytes
  LayerQty: number
  Stories: number
  StoriesOther: number

  // Doubles
  GutterEastLf: number
  GutterNorthLf: number
  GutterSouthLf: number
  GutterWestLf: number
  IceWaterShieldLf: number
  RoofPitchSevenSqft: number
  RoofPitchTenSqft: number
  RoofPitchZeroSqft: number
  RoofStoryOneSqft: number
  RoofStoryTwoSqft: number
  SoffitDepthLf: number
  TarpInstallSizeSf: number
  TarpResetSizeSf: number
  WindDamageEastFiveSqft: number
  WindDamageEastFourSqft: number
  WindDamageEastOneSqft: number
  WindDamageEastThreeSqft: number
  WindDamageEastTwoSqft: number
  WindDamageNorthFiveSqft: number
  WindDamageNorthFourSqft: number
  WindDamageNorthOneSqft: number
  WindDamageNorthThreeSqft: number
  WindDamageNorthTwoSqft: number
  WindDamageSouthFiveSqft: number
  WindDamageSouthFourSqft: number
  WindDamageSouthOneSqft: number
  WindDamageSouthThreeSqft: number
  WindDamageSouthTwoSqft: number
  WindDamageWestFiveSqft: number
  WindDamageWestFourSqft: number
  WindDamageWestOneSqft: number
  WindDamageWestThreeSqft: number
  WindDamageWestTwoSqft: number

  // Shorts
  DripEdgeEaveQty: number
  DripEdgeEaveQtyDamaged: number
  DripEdgeRakeQty: number
  DripEdgeRakeQtyDamaged: number
  FasciaSize: number
  FasciaSizeOther: number
  HailDamageDisagreeEast: number
  HailDamageDisagreeNorth: number
  HailDamageDisagreeSouth: number
  HailDamageDisagreeWest: number
  HailDamageEastSf: number
  HailDamageNorthSf: number
  HailDamageSouthSf: number
  HailDamageWestSf: number
  HailTestSizeEast: number
  HailTestSizeNorth: number
  HailTestSizeSouth: number
  HailTestSizeWest: number
  OtherDamageEast: number
  OtherDamageNorth: number
  OtherDamageSouth: number
  OtherDamageWest: number
  ShingleWidthSf: number // added 1093
  ValleyMetalQty: number
  ValleyMetalQtyDamaged: number

  // Strings
  AdditionalSummary: string
  BlistersEast: string
  BlistersNorth: string
  BlistersSouth: string
  BlistersWest: string
  BrittlenessTestEastPass: string
  BrittlenessTestNorthPass: string
  BrittlenessTestSouthPass: string
  BrittlenessTestWestPass: string
  CloggedGuttersEast: string
  CloggedGuttersNorth: string
  CloggedGuttersSouth: string
  CloggedGuttersWest: string
  CuppedEast: string
  CuppedNorth: string
  CuppedSouth: string
  CuppedWest: string
  DeckingRottedEast: string
  DeckingRottedNorth: string
  DeckingRottedSouth: string
  DeckingRottedWest: string
  FasciaDamaged: string
  FasciaMaterial: string
  FasciaMaterialOther: string
  FeltDescription: string
  FlashingNotSealedEast: string
  FlashingNotSealedNorth: string
  FlashingNotSealedNotes: string
  FlashingNotSealedSouth: string
  FlashingNotSealedWest: string
  FreeForm: string
  GranuleLossEast: string
  GranuleLossNorth: string
  GranuleLossSouth: string
  GranuleLossWest: string
  GutterDescription: string
  GutterMaterial: string
  GutterMaterialOther: string
  GuttersDamage: string
  GutterSize: string
  GutterSizeOther: string
  InstallationErrorDescription: string
  InstallationErrorDescriptionOther: string
  LayerType: string
  LayerTypeOther: string
  ManufacturedMarksEast: string
  ManufacturedMarksNorth: string
  ManufacturedMarksSouth: string
  ManufacturedMarksWest: string
  MechanicalMarksEast: string
  MechanicalMarksNorth: string
  MechanicalMarksSouth: string
  MechanicalMarksWest: string
  NailPopsEast: string
  NailPopsNorth: string
  NailPopsSouth: string
  NailPopsWest: string
  OtherConditionsDescription: string
  OtherConditionsEast: string
  OtherConditionsName: string
  OtherConditionsNorth: string
  OtherConditionsSouth: string
  OtherConditionsWest: string
  OutBuildingNotes: string
  PitchEast: string
  PitchEastOther: string
  PitchNorth: string
  PitchNorthOther: string
  PitchSouth: string
  PitchSouthOther: string
  PitchWest: string
  PitchWestOther: string
  PriorRepairs: string
  PriorRepairsEast: string
  PriorRepairsNorth: string
  PriorRepairsSouth: string
  PriorRepairsWest: string
  RoofAgeMonths: string
  RoofAgeYears: string
  RoofDebrisEast: string
  RoofDebrisNorth: string
  RoofDebrisSouth: string
  RoofDebrisWest: string
  RoofMaterial: string
  RoofMaterialOther: string
  RoofObservations: string
  RoofType: string
  RoofTypeOther: string
  ShingleType: string
  StormDamageType: string
  StormDamageTypeOther: string
  StormDirection: string
  ThermalCrackingEast: string
  ThermalCrackingNorth: string
  ThermalCrackingSouth: string
  ThermalCrackingWest: string
  ValleyMetalMaterial: string
  ValleyType: string
}
