export interface InspectionRoofDamagedItem {
  // Keys
  Id: number
  PropertyInspectionFormId: number

  // Dates
  CreatedOn: Date
  LastModifiedOn: Date

  // Booleans
  BoxVentsPainted: boolean
  BoxVentsPresent: boolean
  CanVentsPainted: boolean
  CanVentsPresent: boolean
  ChimneyCapLargePainted: boolean
  ChimneyCapLargePresent: boolean
  ChimneyCapMediumPainted: boolean
  ChimneyCapMediumPresent: boolean
  ChimneyCapSmallPainted: boolean
  ChimneyCapSmallPresent: boolean
  ChimneyFlashingLargePainted: boolean
  ChimneyFlashingLargePresent: boolean
  ChimneyFlashingMediumPainted: boolean
  ChimneyFlashingMediumPresent: boolean
  ChimneyFlashingSmallPainted: boolean
  ChimneyFlashingSmallPresent: boolean
  DripEdgeEavePainted: boolean
  DripEdgeEavePresent: boolean
  DripEdgeRakePainted: boolean
  DripEdgeRakePresent: boolean
  DryerExhaustPainted: boolean
  DryerExhaustPresent: boolean // NOTE: added 1093
  FlashingPainted: boolean
  FlashingPresent: boolean
  FlatRoofScupperDrainPainted: boolean
  FlatRoofScupperDrainPresent: boolean // added 1093
  GableVentPresent: boolean
  HvacEightPainted: boolean
  HvacEightPresent: boolean
  HvacFourPainted: boolean
  HvacFourPresent: boolean
  HvacOtherPainted: boolean
  HvacOtherPresent: boolean
  HvacSixPainted: boolean
  HvacSixPresent: boolean
  IceShieldPresent: boolean
  LeadPipebootPainted: boolean
  LeadPipebootPresent: boolean
  MastheadPainted: boolean
  MastheadPresent: boolean
  OffRidgeVentsPresent: boolean
  OtherPresent: boolean
  PlasticPipebootPainted: boolean
  PlasticPipebootPresent: boolean
  PowerVentCoversPainted: boolean
  PowerVentCoversPresent: boolean
  PowerVentsPainted: boolean
  PowerVentsPresent: boolean
  RainDivertersPresent: boolean
  RidgeVentsPainted: boolean
  RidgeVentsPresent: boolean
  SatelliteDishPresent: boolean
  SkylightsPainted: boolean
  SkylightsPresent: boolean
  SoffitVentsPainted: boolean
  SoffitVentsPresent: boolean
  SolarPanelPainted: boolean
  SolarPanelPresent: boolean // added 1093
  SwampCoolerPainted: boolean
  SwampCoolerPresent: boolean // added 1093
  TurbinesPainted: boolean
  TurbinesPresent: boolean
  ValleyMetalPainted: boolean
  ValleyMetalPresent: boolean

  // Shorts
  BoxVentsQty: number
  BoxVentsQtyDamaged: number
  CanVentsQty: number
  CanVentsQtyDamaged: number
  ChimneyCapLargeQty: number
  ChimneyCapLargeQtyDamaged: number
  ChimneyCapMediumQty: number
  ChimneyCapMediumQtyDamaged: number
  ChimneyCapSmallQty: number
  ChimneyCapSmallQtyDamaged: number
  ChimneyFlashingLargeQty: number
  ChimneyFlashingLargeQtyDamaged: number
  ChimneyFlashingMediumQty: number
  ChimneyFlashingMediumQtyDamaged: number
  ChimneyFlashingSmallQty: number
  ChimneyFlashingSmallQtyDamaged: number
  DripEdgeEaveQty: number
  DripEdgeEaveQtyDamaged: number
  DripEdgeRakeQty: number
  DripEdgeRakeQtyDamaged: number
  DryerExhaustQty: number
  DryerExhaustQtyDamaged: number
  FlashingQty: number
  FlashingQtyDamaged: number
  FlatRoofScupperDrainQty: number
  FlatRoofScupperDrainQtyDamaged: number
  GableVentQty: number
  GableVentQtyDamaged: number
  HvacEightQty: number
  HvacEightQtyDamaged: number
  HvacFourQty: number
  HvacFourQtyDamaged: number

  //
  HvacOtherQty: number
  HvacOtherQtyDamaged: number
  HvacOtherSize: number

  HvacSixQty: number
  HvacSixQtyDamaged: number
  IceShieldQty: number
  IceShieldQtyDamaged: number
  LeadPipebootQty: number
  LeadPipebootQtyDamaged: number
  MastheadQty: number
  MastheadQtyDamaged: number
  OffRidgeVentsQty: number
  OffRidgeVentsQtyDamaged: number
  OtherQty: number
  OtherQtyDamaged: number
  PlasticPipebootQty: number
  PlasticPipebootQtyDamaged: number
  PowerVentCoversQty: number
  PowerVentCoversQtyDamaged: number
  PowerVentsQty: number
  PowerVentsQtyDamaged: number
  RainDivertersQty: number
  RainDivertersQtyDamaged: number
  RidgeVentsQty: number
  RidgeVentsQtyDamaged: number
  SatelliteDishQty: number
  SatelliteDishQtyDamaged: number
  SkylightsQty: number
  SkylightsQtyDamaged: number
  SoffitVentsQty: number
  SoffitVentsQtyDamaged: number
  SolarPanelQty: number
  SolarPanelQtyDamaged: number
  SwampCoolerQty: number
  SwampCoolerQtyDamaged: number
  TurbinesQty: number
  TurbinesQtyDamaged: number
  ValleyMetalQty: number
  ValleyMetalQtyDamaged: number

  // Strings
  BoxVentsMaterial: String
  OffRidgeVentsMaterial: String // added 1093
  PowerVentCoversMaterial: String
  PowerVentsMaterial: String
  RidgeVentsMaterial: String
  ValleyMetalMaterial: String
}
