export enum ReportType {
  AllstateLadderAssist,
  AllstateVirtual,
  LadderAssistOther,
  DirectInspectionShingles,
  DirectInspectionNoBt,
  DirectInspectionAsphaltRoof,
  DirectInspectionTile,
  DirectInspectionBituminousMembranes,
  DirectInspectionMetal,
  DirectInspectionWood,
  DirectInspectionCAStateAutoAssociation,
  DirectInspectionNoTestSquares,
  HIC,
}
