export enum Roles {
  Administrator = 1,
  Scheduler = 2,
  AdminSupport = 3,
  Bookkeeper = 4,
  ServiceTech = 5,
  ServiceTech2 = 6,
  ServiceManager = 7,
  InsuranceAdjuster = 8,
  BillingContact = 9,
  AdjusterDirector = 10,
  AdjusterManager = 11,
  ServiceDirector = 12,
  Eagleview = 13,
}
