export interface RoofComponentSection {
  BoxVentsMaterial: string
  BoxVentsPainted: string
  BoxVentsQty?: number
  BoxVentsQtyDamaged?: number
  CanVentsPainted: string
  CanVentsQty?: number
  CanVentsQtyDamaged?: number
  ChimneyCapPainted: string
  ChimneyCapQty?: number
  ChimneyCapQtyDamaged?: number
  ChimneyFlashingLargePainted: string
  ChimneyFlashingLargeQty?: number
  ChimneyFlashingLargeQtyDamaged?: number
  ChimneyFlashingMediumPainted: string
  ChimneyFlashingMediumQty?: number
  ChimneyFlashingMediumQtyDamaged?: number
  ChimneyFlashingSmallPainted: string
  ChimneyFlashingSmallQty?: number
  ChimneyFlashingSmallQtyDamaged?: number
  DripEdgePainted: string
  DripEdgeQty?: number
  DripEdgeQtyDamaged?: number
  FlashingPainted: string
  FlashingQty?: number
  FlashingQtyDamaged?: number
  GableVentQty?: number
  GableVentQtyDamaged?: number
  HvacFourPainted: string
  HvacFourQty?: number
  HvacFourQtyDamaged?: number
  HvacSixPainted: string
  HvacSixQty?: number
  HvacSixQtyDamaged?: number
  HvacEightPainted: string
  HvacEightQty?: number
  HvacEightQtyDamaged?: number
  IceShieldQty?: number
  IceShieldQtyDamaged?: number
  MastheadPainted: string
  MastheadQty?: number
  MastheadQtyDamaged?: number
  OtherQty?: number
  OtherQtyDamaged?: number
  PipebootMaterial: string
  PipebootPainted: string
  PipebootQty?: number
  PipebootQtyDamaged?: number
  PowerVentCoversMaterial: string
  PowerVentCoversQty?: number
  PowerVentCoversQtyDamaged?: number
  PowerVentCoversPainted: string
  PowerVentsMaterial: string
  PowerVentsQty?: number
  PowerVentsQtyDamaged?: number
  PowerVentsPainted: string
  RainDivertersQty?: number
  RainDivertersQtyDamaged?: number
  RidgeVentsPainted: string
  RidgeVentsQty?: number
  RidgeVentsQtyDamaged?: number
  RidgeVentsMaterial: string
  SatelliteDishPainted: string
  SatelliteDishQty?: number
  SatelliteDishQtyDamaged?: number
  SkylightsPainted: string
  SkylightsQty?: number
  SkylightsQtyDamaged?: number
  SoffitVentsPainted: string
  SoffitVentsQty?: number
  SoffitVentsQtyDamaged?: number
  TurbinesPainted: string
  TurbinesQty?: number
  TurbinesQtyDamaged?: number
  ValleyMetalMaterial: string
  ValleyMetalPainted: string
  ValleyMetalQty?: number
  ValleyMetalQtyDamaged?: number
}
