export const designSystemsMenu = [
  {
    title: 'Design Systems',
    class: 'text-vue-three',
    hidden: false,
    hiddenOnCollapse: false,
    child: [
      {
        title: 'Examples',
        href: 'https://atlassian.design/components',
        external: true,
        hidden: false,
        child: [
          {
            title: 'Atlassian',
            href: 'https://atlassian.design/components',
            external: true,
            hidden: false,
          },
          {
            title: 'Bootstrap 5',
            href: 'https://getbootstrap.com/docs/5.1/components/',
            external: true,
            hidden: false,
          },
          {
            title: 'Bootstrap 4',
            href: 'https://getbootstrap.com/docs/4.6/components/',
            external: true,
            hidden: false,
          },
          {
            title: 'Bulma',
            href: 'https://bulma.io/documentation/components/',
            external: false,
            hidden: false,
          },
          {
            title: 'Carbon (IBM)',
            href: 'https://www.carbondesignsystem.com/components/overview/',
            external: true,
            hidden: false,
          },
          {
            title: 'E*TRADE',
            href: 'https://etrade.design/',
            external: false,
            hidden: false,
          },
          {
            title: 'Fluent (Microsoft)',
            href: 'https://www.microsoft.com/design/fluent/',
            external: false,
            hidden: false,
          },
          {
            title: 'Foundation',
            href: 'https://get.foundation/',
            external: true,
            hidden: false,
          },
          {
            title: 'Human Interface Guidelines (Apple)',
            href: 'https://developer.apple.com/design/human-interface-guidelines/',
            external: true,
            hidden: false,
          },
          {
            title: 'Lightning (Salesforce)',
            href: 'https://www.lightningdesignsystem.com/',
            external: true,
            hidden: false,
          },
          {
            title: 'Material (Google)',
            href: 'https://material.io/',
            external: true,
            hidden: false,
          },
          {
            title: 'Mailchimp',
            href: 'https://ux.mailchimp.com/patterns',
            external: true,
            hidden: false,
          },
          {
            title: 'Polaris (Shopify)',
            href: 'https://polaris.shopify.com/components/get-started',
            external: false,
            hidden: false,
          },
          {
            title: 'Pajamas (GitLab)',
            href: 'https://design.gitlab.com/',
            external: false,
            hidden: false,
          },
          {
            title: 'Primer (GitHub)',
            href: 'https://primer.style/css/',
            external: false,
            hidden: false,
          },
          {
            title: 'Seeds (Sprout Social)',
            href: 'https://seeds.sproutsocial.com/',
            external: true,
            hidden: false,
          },
          {
            title: 'Spectrum (Adobe)',
            href: 'https://spectrum.adobe.com/',
            external: true,
            hidden: false,
          },
          {
            title: 'Uber',
            href: 'https://brand.uber.com/',
            external: true,
            hidden: false,
          },
          {
            title: 'Wonder Blocks (Khan Academy)',
            href: 'https://wonderblocks.khanacademy.org/',
            external: true,
            hidden: false,
          },
        ],
      },
    ],
  },
]
