export const examplesMenu = [
  {
    title: 'Examples',
    hidden: false,
    hiddenOnCollapse: false,
    icon: 'fad fa-book-spells',
    child: [
      {
        title: 'Cards',
        href: '/examples/cards',
        hidden: false,
        hiddenOnCollapse: false,
        child: [
          {
            title: 'Card 1',
            href: '/examples/cards/card-1',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card 2',
            href: '/examples/cards/card-2',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card 3',
            href: '/examples/cards/card-3',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card 4',
            href: '/examples/cards/card-4',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card 5',
            href: '/examples/cards/card-5',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card 6',
            href: '/examples/cards/card-6',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card 7',
            href: '/examples/cards/card-7',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card Header w/Actions',
            href: '/examples/cards/card-header-with-actions',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card Header with Avatar',
            href: '/examples/cards/card-header-with-avatar',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card Header with Description',
            href: '/examples/cards/card-header-with-description',
            hidden: false,
            hiddenOnCollapse: false,
          },
          {
            title: 'Card Row',
            href: '/examples/cards/card-row',
            hidden: false,
            hiddenOnCollapse: false,
          },
        ],
      },
      {
        title: 'Data Tables',
        class: 'text-vue-three',
        hidden: true,
        hiddenOnCollapse: false,
        child: [
          {
            title: 'Kendo UI Grid',
            href: '/examples/kendo-ui/grid',
            external: false,
            hidden: false,
          },
          {
            title: 'Oruga Table',
            href: '/examples/oruga/table',
            external: false,
            hidden: false,
          },
          {
            title: 'vue-dataset',
            href: '/examples/vue-dataset/datatable',
            external: false,
            hidden: false,
          },
          {
            title: 'vuejs-smart-table',
            href: '/examples/vuejs-smart-table/basics',
            external: false,
            hidden: false,
          },
        ],
      },
      {
        title: 'Headless UI',
        class: 'text-vue-three',
        hidden: false,
        hiddenOnCollapse: false,
        child: [
          {
            title: 'Menu (Dropdown)',
            href: '/examples/headless-ui/menu',
            external: false,
            hidden: false,
          },
          {
            title: 'Listbox (Select)',
            href: '/examples/headless-ui/listbox',
            external: false,
            hidden: false,
          },
          {
            title: 'Switch (Toggle)',
            href: '/examples/headless-ui/switch',
            external: false,
            hidden: false,
          },
          {
            title: 'Disclosure',
            href: '/examples/headless-ui/disclosure',
            external: false,
            hidden: false,
          },
          {
            title: 'Dialog',
            href: '/examples/headless-ui/dialog',
            external: false,
            hidden: false,
          },
          {
            title: 'Popover',
            href: '/examples/headless-ui/popover',
            external: false,
            hidden: false,
          },
          {
            title: 'Radio Group',
            href: '/examples/headless-ui/radio-group',
            external: false,
            hidden: false,
          },
          {
            title: 'Transition',
            href: '/examples/headless-ui/transition',
            external: false,
            hidden: false,
          },
          {
            title: 'Tabs',
            href: '/examples/headless-ui/tabs',
            external: false,
            hidden: false,
          },
        ],
      },
      {
        title: 'Kendo UI',
        hidden: false,
        child: [
          {
            title: 'Kendo Grid',
            href: '/examples/kendo-ui/grid',
            hidden: false,
          },
          {
            title: 'Column menu',
            href: '/examples/kendo-ui/grids/column-menu',
            hidden: false,
          },
          {
            title: 'Custom cell',
            href: '/examples/kendo-ui/grids/cell-custom',
            hidden: false,
          },
          {
            title: 'Detail row',
            href: '/examples/kendo-ui/grids/detail',
            hidden: false,
          },
          {
            title: 'Column width minimum',
            href: '/examples/kendo-ui/grids/column-width-minimum',
            hidden: false,
          },
          {
            title: 'Column width percentage',
            href: '/examples/kendo-ui/grids/column-width-percentage',
            hidden: false,
          },
          {
            title: 'Selection',
            href: '/examples/kendo-ui/grids/select',
            hidden: false,
          },
        ],
      },
      {
        title: 'Oruga',
        class: 'text-vue-three',
        hidden: false,
        hiddenOnCollapse: false,
        child: [
          {
            title: 'Autocomplete',
            href: '/examples/oruga/autocomplete',
            external: false,
            hidden: false,
          },
          {
            title: 'Button',
            href: '/examples/oruga/button',
            external: false,
            hidden: false,
          },
          {
            title: 'Dropdown',
            href: '/examples/oruga/dropdown',
            external: false,
            hidden: false,
          },
          {
            title: 'Carousel',
            href: '/examples/oruga/carousel',
            external: false,
            hidden: false,
          },
          {
            title: 'Field',
            href: '/examples/oruga/field',
            external: false,
            hidden: false,
          },
          {
            title: 'Modal',
            href: '/examples/oruga/modal',
            external: false,
            hidden: false,
          },
          {
            title: 'Upload',
            href: '/examples/oruga/upload',
            external: false,
            hidden: false,
          },
          {
            title: 'Table',
            href: '/examples/oruga/table',
            external: false,
            hidden: false,
          },
        ],
      },
    ],
  },
]
